import type { MarkovConfig } from "@/types/simulation";

export const MARKOV_PRESETS: Record<string, MarkovConfig> = {
  casual_game: {
    events: [
      { name: "AppOpen", color: "#6366f1" },
      { name: "TutorialStarted", color: "#8b5cf6" },
      { name: "TutorialCompleted", color: "#3b82f6" },
      { name: "LevelStarted", color: "#0ea5e9" },
      { name: "LevelCompleted", color: "#10b981" },
      { name: "LevelFailed", color: "#ef4444" },
      { name: "AdWatched", color: "#f59e0b" },
      { name: "PurchaseMade", color: "#e11d48" },
    ],
    start: { AppOpen: 0.7, LevelStarted: 0.3 },
    transitions: {
      AppOpen: { TutorialStarted: 0.4, LevelStarted: 0.5, "[end]": 0.1 },
      TutorialStarted: { TutorialCompleted: 0.75, "[end]": 0.25 },
      TutorialCompleted: { LevelStarted: 0.9, "[end]": 0.1 },
      LevelStarted: { LevelCompleted: 0.55, LevelFailed: 0.35, "[end]": 0.1 },
      LevelCompleted: {
        LevelStarted: 0.5,
        AdWatched: 0.2,
        PurchaseMade: 0.05,
        "[end]": 0.25,
      },
      LevelFailed: { LevelStarted: 0.4, AdWatched: 0.3, "[end]": 0.3 },
      AdWatched: { LevelStarted: 0.7, "[end]": 0.3 },
      PurchaseMade: { LevelStarted: 0.8, "[end]": 0.2 },
    },
  },

  gaming_hardcore: {
    events: [
      { name: "Login", color: "#6366f1" },
      { name: "MatchStarted", color: "#8b5cf6" },
      { name: "MatchWon", color: "#10b981" },
      { name: "MatchLost", color: "#ef4444" },
      { name: "ItemCrafted", color: "#f59e0b" },
      { name: "GuildJoined", color: "#3b82f6" },
      { name: "LeaderboardViewed", color: "#0ea5e9" },
      { name: "PurchaseMade", color: "#e11d48" },
    ],
    start: { Login: 1.0 },
    transitions: {
      Login: {
        MatchStarted: 0.7,
        ItemCrafted: 0.15,
        LeaderboardViewed: 0.1,
        "[end]": 0.05,
      },
      MatchStarted: { MatchWon: 0.45, MatchLost: 0.5, "[end]": 0.05 },
      MatchWon: {
        MatchStarted: 0.6,
        ItemCrafted: 0.15,
        LeaderboardViewed: 0.15,
        "[end]": 0.1,
      },
      MatchLost: {
        MatchStarted: 0.55,
        ItemCrafted: 0.1,
        PurchaseMade: 0.05,
        "[end]": 0.3,
      },
      ItemCrafted: { MatchStarted: 0.6, GuildJoined: 0.1, "[end]": 0.3 },
      GuildJoined: { MatchStarted: 0.7, "[end]": 0.3 },
      LeaderboardViewed: { MatchStarted: 0.6, "[end]": 0.4 },
      PurchaseMade: { MatchStarted: 0.8, "[end]": 0.2 },
    },
  },

  saas: {
    events: [
      { name: "SignUp", color: "#6366f1" },
      { name: "EmailVerified", color: "#8b5cf6" },
      { name: "Onboarded", color: "#3b82f6" },
      { name: "ProjectCreated", color: "#0ea5e9" },
      { name: "ItemCreated", color: "#10b981" },
      { name: "InviteSent", color: "#f59e0b" },
      { name: "InviteAccepted", color: "#84cc16" },
      { name: "UpgradePromptShown", color: "#ec4899" },
      { name: "PlanUpgraded", color: "#e11d48" },
      { name: "PlanDowngraded", color: "#f97316" },
      { name: "Cancelled", color: "#6b7280" },
    ],
    start: { SignUp: 0.6, ItemCreated: 0.4 },
    transitions: {
      SignUp: { EmailVerified: 0.8, "[end]": 0.2 },
      EmailVerified: { Onboarded: 0.85, "[end]": 0.15 },
      Onboarded: { ProjectCreated: 0.7, "[end]": 0.3 },
      ProjectCreated: { ItemCreated: 0.75, InviteSent: 0.1, "[end]": 0.15 },
      ItemCreated: {
        ItemCreated: 0.28,
        InviteSent: 0.1,
        UpgradePromptShown: 0.15,
        Cancelled: 0.02,
        "[end]": 0.45,
      },
      InviteSent: { InviteAccepted: 0.5, "[end]": 0.5 },
      InviteAccepted: { "[end]": 1.0 },
      UpgradePromptShown: { PlanUpgraded: 0.3, "[end]": 0.7 },
      PlanUpgraded: { PlanDowngraded: 0.05, "[end]": 0.95 },
      PlanDowngraded: { "[end]": 1.0 },
      Cancelled: { "[end]": 1.0 },
    },
  },

  ecommerce: {
    events: [
      { name: "SessionStarted", color: "#6366f1" },
      { name: "ProductViewed", color: "#8b5cf6" },
      { name: "SearchPerformed", color: "#3b82f6" },
      { name: "AddedToCart", color: "#0ea5e9" },
      { name: "CheckoutStarted", color: "#f59e0b" },
      { name: "OrderPlaced", color: "#10b981" },
      { name: "ReviewLeft", color: "#84cc16" },
    ],
    start: { SessionStarted: 0.7, SearchPerformed: 0.3 },
    transitions: {
      SessionStarted: {
        ProductViewed: 0.55,
        SearchPerformed: 0.35,
        "[end]": 0.1,
      },
      SearchPerformed: { ProductViewed: 0.65, "[end]": 0.35 },
      ProductViewed: {
        ProductViewed: 0.25,
        AddedToCart: 0.3,
        SearchPerformed: 0.15,
        "[end]": 0.3,
      },
      AddedToCart: { CheckoutStarted: 0.55, ProductViewed: 0.25, "[end]": 0.2 },
      CheckoutStarted: { OrderPlaced: 0.7, "[end]": 0.3 },
      OrderPlaced: { ReviewLeft: 0.2, "[end]": 0.8 },
      ReviewLeft: { "[end]": 1.0 },
    },
  },

  retail: {
    events: [
      { name: "StoreVisit", color: "#6366f1" },
      { name: "ProductScanned", color: "#8b5cf6" },
      { name: "CouponApplied", color: "#f59e0b" },
      { name: "AddedToCart", color: "#0ea5e9" },
      { name: "PurchaseCompleted", color: "#10b981" },
      { name: "LoyaltyPointsEarned", color: "#84cc16" },
      { name: "ReturnInitiated", color: "#ef4444" },
    ],
    start: { StoreVisit: 1.0 },
    transitions: {
      StoreVisit: { ProductScanned: 0.6, CouponApplied: 0.15, "[end]": 0.25 },
      ProductScanned: { AddedToCart: 0.5, ProductScanned: 0.25, "[end]": 0.25 },
      CouponApplied: { AddedToCart: 0.7, "[end]": 0.3 },
      AddedToCart: {
        PurchaseCompleted: 0.65,
        CouponApplied: 0.1,
        "[end]": 0.25,
      },
      PurchaseCompleted: {
        LoyaltyPointsEarned: 0.55,
        ReturnInitiated: 0.05,
        "[end]": 0.4,
      },
      LoyaltyPointsEarned: { "[end]": 1.0 },
      ReturnInitiated: { "[end]": 1.0 },
    },
  },

  marketplace: {
    events: [
      { name: "Browse", color: "#6366f1" },
      { name: "ListingViewed", color: "#8b5cf6" },
      { name: "SellerContacted", color: "#3b82f6" },
      { name: "OfferMade", color: "#f59e0b" },
      { name: "OfferAccepted", color: "#10b981" },
      { name: "PaymentSent", color: "#e11d48" },
      { name: "ReviewLeft", color: "#84cc16" },
      { name: "ListingCreated", color: "#0ea5e9" },
    ],
    start: { Browse: 0.65, ListingCreated: 0.35 },
    transitions: {
      Browse: { ListingViewed: 0.6, "[end]": 0.4 },
      ListingViewed: { SellerContacted: 0.3, ListingViewed: 0.3, "[end]": 0.4 },
      SellerContacted: { OfferMade: 0.5, "[end]": 0.5 },
      OfferMade: { OfferAccepted: 0.55, "[end]": 0.45 },
      OfferAccepted: { PaymentSent: 0.85, "[end]": 0.15 },
      PaymentSent: { ReviewLeft: 0.4, "[end]": 0.6 },
      ReviewLeft: { "[end]": 1.0 },
      ListingCreated: { "[end]": 1.0 },
    },
  },

  dating: {
    events: [
      { name: "ProfileViewed", color: "#6366f1" },
      { name: "LikeSent", color: "#ec4899" },
      { name: "SuperLikeSent", color: "#e11d48" },
      { name: "Matched", color: "#10b981" },
      { name: "MessageSent", color: "#3b82f6" },
      { name: "DateScheduled", color: "#f59e0b" },
      { name: "PremiumUpgraded", color: "#8b5cf6" },
    ],
    start: { ProfileViewed: 1.0 },
    transitions: {
      ProfileViewed: {
        LikeSent: 0.35,
        SuperLikeSent: 0.05,
        ProfileViewed: 0.4,
        "[end]": 0.2,
      },
      LikeSent: { Matched: 0.15, ProfileViewed: 0.6, "[end]": 0.25 },
      SuperLikeSent: { Matched: 0.35, ProfileViewed: 0.5, "[end]": 0.15 },
      Matched: { MessageSent: 0.6, "[end]": 0.4 },
      MessageSent: { MessageSent: 0.4, DateScheduled: 0.2, "[end]": 0.4 },
      DateScheduled: { "[end]": 1.0 },
      PremiumUpgraded: { ProfileViewed: 0.8, "[end]": 0.2 },
    },
  },

  streaming: {
    events: [
      { name: "AppOpened", color: "#6366f1" },
      { name: "ContentBrowsed", color: "#8b5cf6" },
      { name: "ContentStarted", color: "#3b82f6" },
      { name: "ContentCompleted", color: "#10b981" },
      { name: "ContentPaused", color: "#f59e0b" },
      { name: "SearchPerformed", color: "#0ea5e9" },
      { name: "WatchlistUpdated", color: "#84cc16" },
      { name: "SubscriptionUpgraded", color: "#e11d48" },
    ],
    start: { AppOpened: 0.7, ContentBrowsed: 0.3 },
    transitions: {
      AppOpened: { ContentBrowsed: 0.55, SearchPerformed: 0.3, "[end]": 0.15 },
      ContentBrowsed: {
        ContentStarted: 0.5,
        WatchlistUpdated: 0.15,
        SearchPerformed: 0.2,
        "[end]": 0.15,
      },
      SearchPerformed: {
        ContentStarted: 0.5,
        ContentBrowsed: 0.35,
        "[end]": 0.15,
      },
      ContentStarted: {
        ContentCompleted: 0.55,
        ContentPaused: 0.3,
        "[end]": 0.15,
      },
      ContentCompleted: {
        ContentBrowsed: 0.5,
        ContentStarted: 0.3,
        "[end]": 0.2,
      },
      ContentPaused: { ContentStarted: 0.55, "[end]": 0.45 },
      WatchlistUpdated: { ContentBrowsed: 0.6, "[end]": 0.4 },
      SubscriptionUpgraded: { ContentBrowsed: 0.8, "[end]": 0.2 },
    },
  },

  social: {
    events: [
      { name: "FeedViewed", color: "#6366f1" },
      { name: "PostCreated", color: "#10b981" },
      { name: "PostLiked", color: "#ec4899" },
      { name: "CommentLeft", color: "#3b82f6" },
      { name: "UserFollowed", color: "#8b5cf6" },
      { name: "StoryViewed", color: "#f59e0b" },
      { name: "MessageSent", color: "#0ea5e9" },
      { name: "NotificationOpened", color: "#84cc16" },
    ],
    start: { FeedViewed: 0.6, NotificationOpened: 0.4 },
    transitions: {
      FeedViewed: {
        PostLiked: 0.3,
        CommentLeft: 0.1,
        StoryViewed: 0.2,
        PostCreated: 0.1,
        MessageSent: 0.1,
        "[end]": 0.2,
      },
      PostCreated: { FeedViewed: 0.6, "[end]": 0.4 },
      PostLiked: { FeedViewed: 0.5, UserFollowed: 0.1, "[end]": 0.4 },
      CommentLeft: { FeedViewed: 0.55, "[end]": 0.45 },
      UserFollowed: { FeedViewed: 0.6, "[end]": 0.4 },
      StoryViewed: { StoryViewed: 0.4, FeedViewed: 0.3, "[end]": 0.3 },
      MessageSent: { MessageSent: 0.35, FeedViewed: 0.35, "[end]": 0.3 },
      NotificationOpened: { FeedViewed: 0.55, PostLiked: 0.15, "[end]": 0.3 },
    },
  },

  fintech: {
    events: [
      { name: "AppOpened", color: "#6366f1" },
      { name: "BalanceChecked", color: "#8b5cf6" },
      { name: "TransferInitiated", color: "#3b82f6" },
      { name: "TransferCompleted", color: "#10b981" },
      { name: "BillPaid", color: "#f59e0b" },
      { name: "InvestmentViewed", color: "#0ea5e9" },
      { name: "InvestmentMade", color: "#e11d48" },
      { name: "SupportContacted", color: "#6b7280" },
    ],
    start: { AppOpened: 1.0 },
    transitions: {
      AppOpened: {
        BalanceChecked: 0.5,
        TransferInitiated: 0.2,
        BillPaid: 0.15,
        InvestmentViewed: 0.1,
        "[end]": 0.05,
      },
      BalanceChecked: {
        TransferInitiated: 0.25,
        BillPaid: 0.2,
        InvestmentViewed: 0.15,
        "[end]": 0.4,
      },
      TransferInitiated: {
        TransferCompleted: 0.8,
        SupportContacted: 0.05,
        "[end]": 0.15,
      },
      TransferCompleted: { BalanceChecked: 0.4, "[end]": 0.6 },
      BillPaid: { BalanceChecked: 0.35, "[end]": 0.65 },
      InvestmentViewed: { InvestmentMade: 0.3, "[end]": 0.7 },
      InvestmentMade: { BalanceChecked: 0.5, "[end]": 0.5 },
      SupportContacted: { "[end]": 1.0 },
    },
  },
};

export const MARKOV_PRESET_LABELS: Record<string, string> = {
  casual_game: "🎮 Casual Game",
  gaming_hardcore: "🏆 Hardcore Game",
  saas: "🚀 SaaS",
  ecommerce: "🛒 E-commerce",
  retail: "🏪 Retail",
  marketplace: "🤝 Marketplace",
  dating: "💘 Dating App",
  streaming: "🎬 Streaming",
  social: "📱 Social",
  fintech: "💳 Fintech",
};
