"""DatabaseBackend Protocol and shared data types."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

from pydantic import BaseModel


@dataclass
class ColumnInfo:
    """One column returned by detect_schema()."""

    name: str
    type: str  # raw SQL type string, e.g. "VARCHAR", "BIGINT"


@dataclass
class SchemaInfo:
    """Full schema detection result — mirrors the existing API response shape."""

    tables: list[str]
    events_table: str
    columns: list[ColumnInfo]
    suggestions: dict
    proposed_custom_properties: list[dict]


@runtime_checkable
class DatabaseBackend(Protocol):
    """Interface that every database backend must implement."""

    @property
    def dialect_name(self) -> str: ...

    @property
    def identifier_quote_char(self) -> str: ...

    @property
    def use_pool(self) -> bool: ...

    def parse_credentials(self, raw: dict) -> BaseModel: ...
    def connection_string(self, credentials: BaseModel) -> str | None: ...
    def open(self, credentials: BaseModel, read_only: bool = True) -> Any: ...
    def pool_key(self, connection_id: str, credentials: BaseModel) -> tuple: ...
    def is_connection_error(self, exc: Exception) -> bool: ...
    def get_table_columns(self, conn: Any, table_expr: str) -> frozenset[str]: ...
    def table_exists(self, conn: Any, table_name: str) -> bool: ...
    def get_tables(self, conn: Any) -> list[str]: ...
    def get_columns_for_browse(self, conn: Any, table: str) -> list[str]: ...
    def browse(
        self, conn: Any, catalog: str | None, schema: str | None
    ) -> list[dict]: ...
    def detect_schema(self, conn: Any, events_table_hint: str | None) -> SchemaInfo: ...
    def execute(self, conn: Any, query: str, params: list | None) -> list[tuple]: ...
    def execute_with_columns(
        self, conn: Any, query: str, params: list | None
    ) -> tuple[list[str], list[tuple]]: ...
    def build_events_cte(
        self,
        source_table: str,
        uid_field: str,
        ts_field: str,
        en_field: str,
        custom_props: list[dict],
    ) -> str: ...
    def prepend_events_cte(self, cte_body: str, query: str) -> str: ...
    def date_trunc(self, unit: str, col: str) -> str: ...
    def date_diff_days(self, start: str, end: str) -> str: ...
    def epoch_diff_seconds(self, start: str, end: str) -> str: ...
    def interval_minutes_exceeded(
        self, earlier: str, later: str, minutes: int
    ) -> str: ...
    def string_concat(self, *parts: str) -> str: ...
    def cast_to_text(self, expr: str) -> str: ...
    def json_extract_string(self, col: str, key: str) -> str: ...
    def extract_hour(self, col: str) -> str: ...
    def extract_day_of_week(self, col: str) -> str: ...
    def extract_year(self, col: str) -> str: ...
    def extract_month(self, col: str) -> str: ...
    def extract_week(self, col: str) -> str: ...
    def extract_quarter(self, col: str) -> str: ...
